name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install cross-rs/cross
      run: |
        wget https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz
        tar -xvf cross-x86_64-unknown-linux-gnu.tar.gz
    - name: Build
      run: |
        ./cross build --release
        RUSTFLAGS="-C target-feature=-crt-static" ./cross build --target=x86_64-unknown-linux-musl --release

        mv target/x86_64-unknown-linux-gnu/release/libbinder.so libbinder-glibc.so
        mv target/x86_64-unknown-linux-musl/release/libbinder.so libbinder-musl.so

    - name: Deploy - Create and Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: libbinder*.so
